### ISSUE TITLE
Wrench Distribution

### ISSUE THREAD

**Issue by Saeed-Mansouri** [jrl-umi3218/lipm_walking_controller#30] opened 2021-02-01 21:08 UTC
Hi there,

Based on what you stated in [the paper](https://hal.archives-ouvertes.fr/hal-01875387/document), the foot contact wrench is expressed in the sole and ankle frames in the wrench distribution QP problem. In the LIPM walking controller, you just added some offsets in the sagittal and lateral planes to the foot center position for calculating the position of the ankle frame origin. It means that the ankle offset in the z-direction is omitted in the LIPM codes. I like to know why you didn't consider the z-offset?

  ```
Eigen::Vector3d anklePos(const Sole & sole) const
  {
    if(surfaceName == "LeftFootCenter")
    {
      return p() + sole.leftAnkleOffset.x() * sagittal() + sole.leftAnkleOffset.y() * lateral();
    }
    else if(surfaceName == "RightFootCenter")
    {
      return p() + sole.leftAnkleOffset.x() * sagittal() - sole.leftAnkleOffset.y() * lateral();
    }
    else
    {
      LOG_ERROR("Cannot compute anklePos for surface " << surfaceName);
      return p();
    }
  }
```

**Comment by stephane-caron** [comment] 2021-02-06 16:35
Duplicate of https://github.com/stephane-caron/lipm_walking_controller/discussions/69 (I answered there).

**Closed by stephane-caron** 2021-02-06 16:35 UTC
