### ISSUE TITLE
Foot damping control

### ISSUE THREAD

**Issue by Saeed-Mansouri** [jrl-umi3218/lipm_walking_controller#32] opened 2021-02-01 21:48 UTC
Hi there,

Prof. Kajita introduced foot damping control in his [paper](https://ieeexplore.ieee.org/document/5651082). There is a second term on the right-hand side of Eq (14) of Kajita's paper that is not considered in the CoP task applied in the mc_rtc. Why didn't you consider such a term?

**Comment by stephane-caron** [comment] 2021-02-06 16:35
Duplicate of https://github.com/stephane-caron/lipm_walking_controller/discussions/71 (I answered there).

**Closed by stephane-caron** 2021-02-06 16:35 UTC
