### ISSUE TITLE
Getting body joints position and angles

### ISSUE THREAD

**Issue by mohamadmahdavian** [jrl-umi3218/lipm_walking_controller#17] opened 2020-03-10 04:50 UTC
Hi @arntanguy @gergondet @stephane-caron 

I need to get all joints position and orientations in LIPM package while robot is walking, possibly in Controller.cpp code. For example the knee joint position or ankle joint orientation. What is the simplest possible way, without using joint angles and solving Forward Kinematic. Is there any parameter for this?

Thank You

**Comment by stephane-caron** [comment] 2020-03-14 12:58
Closing this issue as duplicate of [that one](https://github.com/jrl-umi3218/mc_rtc/issues/19).

**Closed by stephane-caron** 2020-03-14 12:58 UTC
